### ISSUE TITLE
In game and website documentation error, stacksize() should be size() when called as a method

### ISSUE THREAD

**Issue by WhiteFire-Sondergaard** [CyclopsMC/IntegratedScripting#13]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Error in documentation example giving a method name stacksize() where the correct method name is size().

#### Steps to reproduce the problem:

1. Look at the documentation here:  https://integrateddynamics.rubensworks.net/book/tutorials/tutorials/integratedscripting/functions.html which at the time of this writing has the following:

```
function filterItemMethods(item) {
  return item.isStackable() && item.stacksize() >= 16;
}
```

Error is also in the in-game book.

#### Expected behaviour:

I would expect the code to be the functional code:

```
function filterItemMethods(item) {
  return item.isStackable() && item.size() >= 16;
}
```

____

#### Versions:

- This mod: 1.0.2 
- Minecraft: 1.20.1
- Forge: 47.2.30

**Comment by rubensworks** [comment]
Thanks for reporting!
