### ISSUE TITLE
1.20.1 does not generate config (may apply to other versions

### ISSUE THREAD

**Issue by walksanatora** [CyclopsMC/IntegratedScripting#14]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Integrated scripting despite having configs semingly implemented. does nothing an never creates a config file
#### Steps to reproduce the problem:

1. install integrated scripting + dependicies
2. make a world
3. check config and serverconfig
4. realize there is no integratedscripting.toml file (or any config for integrated scripting)

#### Expected behaviour:

the config to exists and be able to be changed

____

#### Versions:

- This mod: Integrated Scriptin 1.0.3
- Minecraft: 1.20.1
- Forge: 47.2.32

**Comment by rubensworks** [comment]
Thanks for reporting!
