### ISSUE TITLE
Leaving a variable card in the store referencing a function and you delete everything except a parentheses or brackets the server crashes

### ISSUE THREAD

**Issue by Ajikozau** [CyclopsMC/IntegratedScripting#17]
#### Issue type:

- :bug: 

____

#### Short description:

Whenever you leave a variable card inside a variable store with a reference to a script variable, have the variable card applied to another card and the third card is active in the network and delete all the function except a parentheses or curly brackets (haven't tried anything else) the server crashes. 
In the modpack I'm currently playing on it removes the display and the inserted card from the game.

#### Steps to reproduce the problem:

- Write a function
- Reference the function in a card
- Apply the function to a second card
- Insert the applied function in a display
- Remove all the function except a brackets or parentheses

#### Expected behaviour:

The display throws an error.

____

#### Versions:

- This mod: 1.0.3
- Minecraft: 1.20.4
- Mod loader version: Neoforge 20.4.237

#### Log file:

Sorry don't have a log for this because I was testing out stuff and lost the log in the process.

**Comment by Ajikozau** [comment]
Incidentally this was the function I was playing around with

```
function test(list, filters) {
  let filteredList = [];
  for (i = 0; i < filters.length; i++) {
    let filterName = idContext.ops.uniquely_namedUniqueName(filters[i]);
    for (i2 = 0; i2 < list.length; i2++) {
      let itemName = idContext.ops.uniquely_namedUniqueName(list[i2]);
      if (filterName === itemName) {
        filteredList.push(filters[i]);
      }
    }
  }
  return filteredList;
}

```

**Comment by rubensworks** [comment]
Can't reproduce this myself unfortunately.
If you (or anyone else reading this) can provide a crashlog, I'm happy to re-open this issue.
