### ISSUE TITLE
Crash while trying to manually set item variable.

### ISSUE THREAD

**Issue by drbleblo** [CyclopsMC/IntegratedScripting#19]
#### Issue type:Crash

- :bug: Bug 

____

#### Short description:
Crashed to desktop while editing a script trying to manually set a variable to an item
Code : let step = {id_item:(id: 'minecraft:arrow')}

#### Steps to reproduce the problem:

1. Create a script with this code:
let step = {id_item:('minecraft:arrow')}
2. Copy step to variable card
3.Put in Display Pannel

#### Expected behaviour:
Error in system 

____

#### Versions:

- This mod: 
- Minecraft: 1.21.1
- Mod loader version: 21.1.71

I know what it says here but I'm certain this is a problem with your mod
#### Log file:

https://pastebin.com/WHACb85Q

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
The crashlog seems unrelated to the problem you describe, as seems to be caused by AE2.
Could you try reproducing the problem without any other mods installed?
