### ISSUE TITLE
Grash when inserting script card in wrong exporter slot

### ISSUE THREAD

**Issue by Hiranus** [CyclopsMC/IntegratedScripting#20]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Game crashes when I insert a card that executes this function into wrong slot in any exporter

``function anvils() {
  return [
      itemByName("minecraft:damaged_anvil"),
      itemByName("minecraft:chipped_anvil"),
      itemByName("minecraft:anvil"),
    ];
}``

#### Steps to reproduce the problem:

1. make card that executes script provided above,
2. insert it into single item slot or predicate exporter 

#### Expected behaviour:

Red X instead of crash.

____

#### Versions:

- This mod: 1.0.6
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.72

#### Log file:
https://pastebin.com/KnvwzJdH

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I haven't been able to reproduce the problem you're describing.
This should have been fixed as of https://github.com/CyclopsMC/IntegratedScripting/issues/9
Are you sure you're using the latest version of all ID mods?
If yes, could you share a video or more details steps to reproduce the problem?

**Comment by Hiranus** [comment]
https://streamable.com/ifbmeg

[latest.log](https://github.com/user-attachments/files/17546002/latest.log)

You can also reach out to me on your Discord. I'm Hiran there.

<blockquote><img src="https://cdn-cf-east.streamable.com/image/ifbmeg.jpg?Expires=1730392345786&Key-Pair-Id=APKAIEYUVEN4EVB2OKEQ&Signature=mokm521uo2BPSTRglJPJpk4dcSl7MRMXkVCTEwM~rplIjwepBOw3-2bBSHM6B8MerdS3-PcMdQCHFsgvNNH3VVZIcyoTl-aeGWSGr3tlVaOgQ63U-SbCsWUVJ15emUK4m1aUIM3M3~oXDBX~nkBZv6p-59M7KWUt5BPt4ClPAZwIi~a-0~tvPSLQtW12xQGkdwp16R4ILu123gcV6iLPg353Mjf0R~EOyMyZ2f79HQP~IjtT3plsJFgTdM3sievPVoS08iKIbWWunt1lqMbUU~khgIPFiI7k1JpgBRkixgNWG0oKy~klgcs8NuJTUPz9TdUI9vq-g8avjBDlC8qOsg__" width="48" align="right"><div>Streamable</div><div><strong><a href="https://streamable.com/ifbmeg">Watch unknown_2024.10.28-17.25 | Streamable</a></strong></div><div>Watch "unknown_2024.10.28-17.25" on Streamable.</div></blockquote>

**Comment by rubensworks** [comment]
Ah, it's the world item exporter. I thought it was the regular item exporter.

**Comment by rubensworks** [comment]
@Hiranus From your video, it also appears you are using an applied function (using `apply3`).
Could you describe the steps that were necessary to create this variable?

**Comment by Hiranus** [comment]
[script0.txt](https://github.com/user-attachments/files/17547390/script0.txt)

This is the script I'm using.

You can pick any function with 3 arguments. Here are some descriptions of parameters
itemsInChamber - list of items from entitiesToItemIds(entities) where "entities" is just a list of items on the floor read by entity reader
itemsToDisenchant - list of items from inventory reader
isChamberDisenchanting - boolean, you can just pass false during your testing
shouldImport*Realized - just functions with same name after running apply on them.

If you want to understand the goal of this script, here is a brief description:
Apotheosis adds disenchanting of items by dropping anvil on obsidian block that has enchanted items and books on it. Goal of this whole contraption is to automate this process. I'm checking if there are any items to disenchant and if there is anything being disenchanted. If nothing is being processed, then I drop stack of books and few items and drop anvil on it.
