### ISSUE TITLE
Crash/Vanish when returning object with a field as null into a display panel.

### ISSUE THREAD

**Issue by FloralSoda** [CyclopsMC/IntegratedScripting#22]
#### Issue type:

- :bug: Bug 

____

#### Short description:
When returning a JSON object that has a field set to null, Gson cannot handle this field and throws an error. In a display panel, this usually results in a crash, but is sometimes error-handled as the display panel getting deleted.

#### Steps to reproduce the problem:

0. Assemble a display panel, variable store, scripting drive and scripting terminal.
1. Create a script with the following contents:
```js
function bad_object() {
  let bad_obj = {};
  bad_obj["foo"] = null;
  return bad_obj;
}
```
2. Create an operator variable card with this script.
3. Apply0 the generated operator
4. Put the new variable card into a display panel 
5. Game crash or display panel vanishes.
#### Expected behaviour:

I believe fields assigned `null` should be filtered out and ignored when converting a json object into nbt, though the exact behaviour of this may need discussion (null can be useful for communication between scripts, but doesn't really exist in NBT)
____

#### Versions:

- This mod: IntegratedScripting 1.0.7
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.89

#### Log file:
https://gist.github.com/FloralSoda/a4e65e108424e83ae3d8ec993e138e73

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by kirjorjos** [comment]
Are you able to test easily if this happens in single player?  I went to look at it in my dev environment and I'm unable to replicate the crash.

**Comment by FloralSoda** [comment]
When I wrote this issue, I was testing it in singleplayer using just scripting and dynamics. The crashes seemed to happen most often when the script was run multiple times over multiple ticks, but it did still happen just 1 operation  too
