### ISSUE TITLE
Delete keyword is not highlighted correctly in editor

### ISSUE THREAD

**Issue by FloralSoda** [CyclopsMC/IntegratedScripting#23]
#### Issue type:

- :bug: Bug 

____

#### Short description:
The [delete keyword](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete) is not highlighted properly. The highlighter seems to pick up the `let` keyword in the middle of the word instead.

#### Steps to reproduce the problem:

1. Open IDE
2. Write delete
3. Delete is not red, but the "let" in the middle of the word is.

#### Expected behaviour:
Delete is a keyword, so it should be highlighted in red.

____

#### Versions:

- This mod: IntegratedScripting 1.0.7
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.89

#### Log file:
N/A

**Comment by rubensworks** [comment]
Thanks for reporting!
