### ISSUE TITLE
I encountered a problem and need help

### ISSUE THREAD

**Issue by GaN8373** [CyclopsMC/IntegratedScripting#24]
#### Issue type:

- :question: Question 

____

#### Question:

1. How do I read the variable card in the variable card box directly? Assuming the variable card ID is 21, should I use idContext.ops.uniquely_namedUniqueName(21)?
2. How do I execute my function? I tried the Display panel and the delayer. I can't execute my function to get the log output

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
> How do I read the variable card in the variable card box directly? Assuming the variable card ID is 21, should I use idContext.ops.uniquely_namedUniqueName(21)?

That is not possible. You need to pass variables to the function when invoking it.

> How do I execute my function? I tried the Display panel and the delayer. I can't execute my function to get the log output

Operators such as `apply` and `apply_n` can be used. Or you can insert the function's variable card inside a predicate-based aspect such as those in Integrated Tunnels.
