### ISSUE TITLE
Variable card resets "Member" property when pulling from terminal

### ISSUE THREAD

**Issue by manaphoenix** [CyclopsMC/IntegratedScripting#25]
#### Issue type:

- :bug: Bug

____

#### Short description:

The variable when put into the scripting terminal slot looks fine, but then when you pull it out it will reset its "member" property. Often to whatever the first word of the js script is. This seems to happen 100% of the time /w new cards and is a 50/50 if updating the card.

#### Steps to reproduce the problem:

1. Attach a terminal
2. Make a script (I used ops, IE. function, but should work for anything as long as its not the first word of the script)
3. Insert a variable card to set it to the correct thing (Function name, const name, etc)
4. pull the card out (I clicked and pulled out not shift clicked)
5. look at card, and see its "Member" property is reset to the first word, Function, let, const... etc...

#### Expected behaviour:

1. Attach a terminal
2. Make a script (I used ops, IE. function, but should work for anything as long as its not the first word of the script)
3. Insert a variable card to set it to the correct thing (Function name, const name, etc)
4. pull the card out (I clicked and pulled out not shift clicked)
5. look at card, and see its "Member" property is what you set it to.

____

#### Versions:

- This mod: integratedscripting-1.21.1-neoforge-1.0.8
- Minecraft: 1.21.1
- Mod loader version: Neoforge 21.1.90

#### Log file:

- No crash, so no crash file, can upload log if needed though.

**Comment by rubensworks** [comment]
Thanks for reporting!
