### ISSUE TITLE
use try{...}catch(e){...} can crash

### ISSUE THREAD

**Issue by GaN8373** [CyclopsMC/IntegratedScripting#27]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

use script:
```javascript

function f1(itemStackElement,networkStackExpr) {
    try {
        for (const element of itemStackElement) {
            let operatorApply = idContext.ops.operatorApply(networkStackExpr, element);
            if (operatorApply < 512) {
                console.log(`Operator Apply: ${operatorApply}`);

                return operatorApply;
            }

        }
    }catch(e) {
        console.log(e);
    }
}
```

#### Expected behaviour:

____

#### Versions:

- This mod: 1.0.7-146
- Minecraft: 1.21.1
- Mod loader version: neoforge - 21.1.57

#### Log file:

[crash-2024-12-23_00.02.08-server.txt](https://github.com/user-attachments/files/18222504/crash-2024-12-23_00.02.08-server.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Jack-McKalling** [comment]
Could you reproduce what you did to get this, in an environment with just Scripting installed (with dependencies)?
It looks like this might be a clear bug already but just in case.

**Comment by GaN8373** [comment]
[crash-2024-12-23_12.49.29-server.txt](https://github.com/user-attachments/files/18225205/crash-2024-12-23_12.49.29-server.txt)
[saves.zip](https://github.com/user-attachments/files/18225213/saves.zip)
i directly use throw new Error(). 
The main reason for a crash is that no value is returned after catching an error
