### ISSUE TITLE
Script Editor Scrolling

### ISSUE THREAD

**Issue by Kyiki-Nasoka** [CyclopsMC/IntegratedScripting#3]
#### Issue type: Client Crash

- :bug: Bug 

____

#### Steps to reproduce the problem: 

1. Enter enough lines for script editor to need to scroll

#### Expected behaviour: Page scrolling

____

#### Versions:1.19.2 - 43.3.5

- This mod: integratedscripting-1.19.2-1.0.0-31
- Minecraft: 1.19.2
- Forge: 43.3.5

**Comment by rubensworks** [comment]
Ah, that's just a CyclopsCore version issue. Will load up the latest version to the server.
