### ISSUE TITLE
Crash on text input

### ISSUE THREAD

**Issue by Kyiki-Nasoka** [CyclopsMC/IntegratedScripting#4]
#### Issue type: Client crash

- :bug: Bug 

____

#### Short description: 
Crash when putting text into scripting field.

#### Steps to reproduce the problem:

1. Network with script storage, script terminal. 
2. Open and click in typing field. When key (This case "f") is pressed, client crashes

#### Expected behaviour:

____

#### Versions:

- This mod: integratedscripting-1.19.2-1.0.0-31
- Minecraft: 1.19.2
- Forge: 43.3.5

**Comment by rubensworks** [comment]
Thanks for reporting!
