### ISSUE TITLE
Syntax error in variables while editing script

### ISSUE THREAD

**Issue by QinomeD** [CyclopsMC/IntegratedScripting#5]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When adding a reassignment (smth like `let str = "test"; str = "test 2"`), the variable card gives me a syntax error (for example in display panels). Reinserting the variable card solves the issue (it's still annoying regardless).

#### Steps to reproduce the problem:

1. Add a variable to your script, for example `let str = "Hi InDy"`
2. Use this variable in a variable card and insert it into a connected display panel
3. The variable's value is displayed properly
4. Reassign the variable in your script, like `str += " and InScripting!"`
5. Display Panel shows an X, hovering over the X in display panel's GUI shows that it's a SyntaxError (depends on what type of variable you are reassigning)

#### Expected behaviour:

New value displays correctly.
____

#### Versions:

- This mod: 1.19.2-1.0.0
- Minecraft: 1.19.2
- Forge: 43.3.7

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Could you share the syntax error message you're getting?

**Comment by QinomeD** [comment]
Sure, one sec!

**Comment by QinomeD** [comment]
![image](https://github.com/CyclopsMC/IntegratedScripting/assets/31182345/742c36ba-715d-4147-b560-48ac51baa655)
![image](https://github.com/CyclopsMC/IntegratedScripting/assets/31182345/9c78b762-0b33-4d06-8d26-627db6ba1ca3)
This is for the number type, for some reason syntax error says there's no `ar` symbol, but I use `arr`, so idk

**Comment by QinomeD** [comment]
![image](https://github.com/CyclopsMC/IntegratedScripting/assets/31182345/3f3fa1a5-b5a1-47d7-a5a0-0665a88de12a)
![image](https://github.com/CyclopsMC/IntegratedScripting/assets/31182345/9a268259-41da-448a-9bf9-ec832c314d09)
This happens for reassigning array values

**Comment by rubensworks** [comment]
The script variable probably got updated while you were typing, at which point the line was not complete yet and would result in a syntax error.
So I don't think the re-assignment itself is the problem.

Not sure yet what a good solution to this could be...

**Comment by QinomeD** [comment]
oh yeah, it's actually not only reassigning, I just didn't really test anything, since just changing the value manually didn't trigger the error

maybe the variable should be updated when the player stops writing?

**Comment by rubensworks** [comment]
Note to self: consider invalidating errored variables, but only those that errored due to the currently edited script.
