### ISSUE TITLE
Please port this mod to 1.18.2

### ISSUE THREAD

**Issue by daniele-bondi** [CyclopsMC/IntegratedScripting#6]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

Like the title says.
I'm playing a 1.18.2 modpack and ID is the "simple" option for moving items around, but having to play pretend functional programmer via the minecraft gui is driving me insane.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Sorry, backporting is not part of my roadmap.
