### ISSUE TITLE
Script crashes the game (When creating/displaying a JS object? Maybe??)

### ISSUE THREAD

**Issue by Iris-xii** [CyclopsMC/IntegratedScripting#8]
#### Issue type:

- :bug: Bug 

____

#### Short description:

This specific script crashes the game when trying to run:
```
function makeBucket(item) {
 // return item.bucket()
 return {a: item.amount() , b: item.bucket() }
}
```
I apologize for the vague issue title, but I actually have no idea what's going on, or which part of this is causing the issue, other than "this makes it happen". As I was just experimenting and poking around, for now I will just, not do that

#### Steps to reproduce the problem:

1. Make that script
2. Use integrated dynamics to apply the function to a fluid
3. Put the resulting card after applying in a display

#### Expected behavior:

Not a crash

____

#### Versions:

- This mod: IntegratedScripting-1.20.1-1.0.1 
- Minecraft: 1.20.1
- Forge: 47.2.21

#### Log file:
https://pastebin.com/esnvwdVJ

Also, I know it's unrelated but really sweet mod, wanted something like this for integrated dynamics for a while! Not being limited in complexity by the point at which variable card spaghetti overwhelms me is going to be really nice

**Comment by rubensworks** [comment]
Thanks for reporting!
